// Project data for filtering
export const projectList = [
  {
    title: "Retail Store POS Application",
    type: "FullStack",
    description: "A scalable e-commerce platform with real-time order tracking and customer management.",
    tech: ["reactjs", "redux", "bootstrap", "nodejs", "mongodb", "vercel","jwt"],
    image: "https://images.pexels.com/photos/3985096/pexels-photo-3985096.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    githubLink: "https://github.com/Thamarai-IND/React-Retail-Store-POS-Application",
  },
  {
    title: "Portfolio Website",
    type: "Frontend",
    description: "Personal portfolio website to showcase skills and projects.",
    tech: ["reactjs", "vite", "typescript", "sass", "tailwind"],
    image: "https://images.pexels.com/photos/4623115/pexels-photo-4623115.jpeg",
    githubLink: "https://github.com/Thamarai-IND/protfolio",
    hostLink: "https://protfolio-beryl-one.vercel.app/",
  },
  {
    title: "User Authentication",
    type: "Backend",
    description: "A robust API gateway for microservices architecture.",
    tech: ["nodejs", "expressjs", "jwt", "passportjs","mongodb"],
    image: "https://images.pexels.com/photos/11337254/pexels-photo-11337254.jpeg",
    githubLink: "https://github.com/Thamarai-IND/Node-Auth",
  },
  {
    title: "Gemini Clone",
    type: "Frontend",
    description: "A robust API gateway for microservices architecture.",
    tech: ["reactjs", "vite", "gemini", "vercel","javascript","html5","css3"],
    image: "https://images.unsplash.com/photo-1710993011904-8f1162b9806d?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    githubLink: "https://github.com/Thamarai-IND/gemini-ai",
    hostLink: "https://gemini-ai-orpin.vercel.app/",
  },
  {
    title: "Payment Integration",
    type: "FullStack",
    description: "A productivity app for managing daily tasks and projects.",
    tech: ["reactjs", "nodejs", "expressjs", "mongodb", "razorpay"],
    image: "https://images.pexels.com/photos/5239803/pexels-photo-5239803.jpeg",
    githubLink: "https://github.com/Thamarai-IND/Razorpay-Checkout",
  },
  {
    title: "Crypto Market Live",
    type: "Frontend",
    description: "A high-converting landing page for a SaaS product.",
    tech: ["reactjs","materialui","javascript", "chartjs", "coingecko", "netlify"],
    image: "https://images.pexels.com/photos/14354118/pexels-photo-14354118.jpeg",
  githubLink: "https://github.com/Thamarai-IND/crypto-market-cap",
  hostLink: "https://crypto-market-cap-api.netlify.app/",
  },
  {
    title: "Everi IGT Website Clone",
    type: "Frontend",
    description: "A high-converting landing page for a SaaS product.",
    tech: ["angularjs","expressjs","typescript", "sass", "materialui", "vercel"],
    image: "https://images.pexels.com/photos/29825627/pexels-photo-29825627.jpeg",
  githubLink: "https://github.com/senvyuha-glitch/everi-webportal-demo",
  hostLink: "https://everi-webportal-demo.vercel.app/",
  },
  {
    title: "Open Weather",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "openweather", "bootstrap", "netlify"],
    image: "https://images.pexels.com/photos/8828681/pexels-photo-8828681.jpeg",
  githubLink: "https://github.com/Thamarai-IND/Weather-App",
  hostLink: "https://auth-service.example.com",
  },
  {
    title: "Angular 18 Sample Code",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["angularjs", "typescript", "bootstrap", "sass", "materialui", "jwt", "vercel"],
    image: "https://images.pexels.com/photos/2653362/pexels-photo-2653362.jpeg",
  githubLink: "https://github.com/Thamarai-IND/angular18",
  hostLink: "https://angular18-gamma.vercel.app/",
  },
  {
    title: "Magazine Card",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["angularjs", "typescript", "html5", "sass", "vercel"],
    image: "https://images.pexels.com/photos/3847620/pexels-photo-3847620.jpeg",
  githubLink: "https://github.com/Thamarai-IND/magazine-card",
  hostLink: "https://magazine-card.vercel.app/",
  },
  {
    title: "Restraunt POS",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "typescript", "tailwind", "sass", "vercel"],
    image: "https://images.pexels.com/photos/12935048/pexels-photo-12935048.jpeg",
  githubLink: "https://github.com/Thamarai-IND/Restaurant-POS",
  hostLink: "https://restaurant-pos-omega-mauve.vercel.app/",
  },
  {
    title: "Tic Tac Toe Game",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["html5", "css3", "javascript", "netlify"],
    image: "https://images.pexels.com/photos/4016535/pexels-photo-4016535.jpeg",
  githubLink: "https://github.com/Thamarai-IND/Tic-Tac-Toe-Game",
  hostLink: "https://tictac-toegame-807bc2.netlify.app/",
  },
  {
    title: "Fun Cricket",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["html5", "css3", "javascript", "vercel", "netlify"],
    image: "https://images.pexels.com/photos/3718433/pexels-photo-3718433.jpeg",
  githubLink: "https://github.com/Thamarai-IND/Mini-Cricket-Fun-App",
  hostLink: "https://mini-cricket-fun-app.vercel.app/",
  },
  {
    title: "Admin Dashboard",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "materialui", "javascript", "chartjs", "netlify"],
    image: "https://images.pexels.com/photos/7947846/pexels-photo-7947846.jpeg",
  githubLink: "https://github.com/Thamarai-IND/admin-dashboard",
  hostLink: "https://admin-dashboard-6aa09d.netlify.app/",
  },
  {
    title: "Add to Cart UI",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "materialui", "javascript", "redux", "netlify"],
    image: "https://images.pexels.com/photos/5650049/pexels-photo-5650049.jpeg",
  githubLink: "https://github.com/Thamarai-IND/redux_fakeshop_api",
  hostLink: "https://redux-state-management-8405b0.netlify.app/",
  },
  {
    title: "React Todo List",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "javascript", "css3", "html5", "netlify"],
    image: "https://images.pexels.com/photos/20279300/pexels-photo-20279300.jpeg",
  githubLink: "https://github.com/Thamarai-IND/Simple-React-ToDoList",
  hostLink: "https://simple-react-todolist-app.netlify.app/",
  },
  {
    title: "React Form Validation",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "javascript", "css3", "html5", "netlify"],
    image: "https://images.pexels.com/photos/2882566/pexels-photo-2882566.jpeg",
  githubLink: "https://github.com/Thamarai-IND/React-Form-Validation",
  hostLink: "https://react-form-validation-12bb13.netlify.app/",
  },
  {
    title: "Pricing Card 1",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "javascript", "css3", "html5", "netlify"],
    image: "https://thamarai-vivid-portfolio.netlify.app/images/pricing.JPG",
  githubLink: "https://github.com/Thamarai-IND/react-pricing-card1",
  hostLink: "https://pricing-card1-a3cb11.netlify.app/",
  },
  {
    title: "Pricing Card 2",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "javascript", "css3", "html5", "netlify"],
    image: "https://images.pexels.com/photos/6441571/pexels-photo-6441571.jpeg",
  githubLink: "https://github.com/Thamarai-IND/react-pricing-card2",
  hostLink: "https://pricing-card2-ac53f1.netlify.app/",
  },
  {
    title: "Blog Page",
    type: "Frontend",
    description: "A secure authentication and authorization service.",
    tech: ["reactjs", "javascript", "materialui", "css3", "html5", "netlify"],
    image: "https://images.pexels.com/photos/4126743/pexels-photo-4126743.jpeg",
  githubLink: "https://github.com/Thamarai-IND/react-blog-pages",
  hostLink: "https://connecting-peoples-blog-1a77dd.netlify.app/",
  },
];
