// Project data for filtering
export const projectList = [
  {
    title: "Retail Store POS Application",
    type: "FullStack",
    description: "A scalable e-commerce platform with real-time order tracking and customer management.",
    tech: ["reactjs", "nodejs", "mongodb", "vercel"],
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c",
    githubLink: "https://github.com/Thamarai-IND/React-Retail-Store-POS-Application",
  },
  {
    title: "Portfolio Website",
    type: "Frontend",
    description: "Personal portfolio website to showcase skills and projects.",
    tech: ["reactjs", "viteLogo", "typescript", "sass"],
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6",
  githubLink: "https://github.com/example/portfolio",
  hostLink: "https://portfolio.example.com",
  },
  {
    title: "API Gateway",
    type: "Backend",
    description: "A robust API gateway for microservices architecture.",
    tech: ["nodejs", "expressjs", "redis", "postgres"],
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
  githubLink: "https://github.com/example/api-gateway",
  hostLink: "https://api-gateway.example.com",
  },
  {
    title: "Task Manager App",
    type: "FullStack",
    description: "A productivity app for managing daily tasks and projects.",
    tech: ["reactjs", "nodejs", "mongodb", "redux"],
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
  githubLink: "https://github.com/example/task-manager",
  hostLink: "https://task-manager.example.com",
  },
  {
    title: "Landing Page",
    type: "Frontend",
    description: "A high-converting landing page for a SaaS product.",
    tech: ["html5", "css3", "javascript"],
    image: "https://images.unsplash.com/photo-1465101178521-c1a9136a3b99",
  githubLink: "https://github.com/example/landing-page",
  hostLink: "https://landing-page.example.com",
  },
  {
    title: "Authentication Service",
    type: "Backend",
    description: "A secure authentication and authorization service.",
    tech: ["nodejs", "expressjs", "mongodb", "jwt"],
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
  githubLink: "https://github.com/example/auth-service",
  hostLink: "https://auth-service.example.com",
  },
];
